### ISSUE TITLE
Request: Kernel with Reiser4 patches for 4.7 with BFS&BFQ-sched and Dell XPS Skylake support

### ISSUE THREAD

**Issue by petter3k** [Sudokamikaze/XKernel-arch#1]
Seeing that it was recently ported to 4.7 can you instead of 4.5 for old-stable, maybe update it to 4.7?

BFS scheduler would preferred for most I think, but maybe put option in PKGBUILD.

I run and XPS 15 9550 core i7-6700HQ, 32GB RAM, NVMe PCIe 512GB SSD, 1080p screen and 84whr battery.

https://reiser4.wiki.kernel.org/index.php/Main_Page

Love your stuff though!

**Comment by Sudokamikaze** [comment]
@petter3k 
old-stable don't be updated to 4.7 because intel_pstate driver is broken in new updates(if you wan't i'll update in other branch)

I'll enable reiser4 when author update patchset to 4.8 

I will create option to select BFS in pkgbuild(in stable branch)

**Comment by Sudokamikaze** [comment]
@petter3k
BFS will not be added to the stable branch since the process of patching 
accompanied by errors

Check out [this](https://github.com/Sudokamikaze/XKernel-arch/commit/829568ffa8fc739e0641b544db32fce395d152b8) commit
Also backported this feature to old-stable
For your Dell with Skylake define in _use_optimization="SKYLAKE"

Tell me if you want xkernel features in the 4.7 kernel

**Comment by petter3k** [comment]
Muqs OR bld pluss reiser4 in kernel for Arch with skylake optimizations would be like a dream!! If you can make that happen I am forever grateful. Hope you can enable in kernel support for XPS/Dell hotkeys  (wmi/hid) :)

Få Outlook for Android<https://aka.ms/ghei36>



On Thu, Nov 3, 2016 at 11:19 PM +0100, "Sudokamikaze" <notifications@github.com<mailto:notifications@github.com>> wrote:


@petter3k<https://github.com/petter3k>
BFS will not be added to the stable branch since the process of patching
accompanied by errors

Check out this<https://github.com/Sudokamikaze/XKernel-arch/commit/829568ffa8fc739e0641b544db32fce395d152b8> commit
Also backported this feature to old-stable
For your Dell with Skylake define in _use_optimization="SKYLAKE"

Tell me if you want xkernel features in the 4.7 kernel

-

**Comment by Sudokamikaze** [comment]
@petter3k 
I will work on it. And about hotkeys, i don't know how to enable hotkeys for your XPS because i have Lenovo g580. sorry :c
Check archwiki or maybe [this](https://ahxxm.com/151.moew/#keyboard-remap-replace-caps-with-ctrl) can helps you

**Comment by Sudokamikaze** [comment]
@petter3k 
You want MUQSS_or_BLD+reiser4+optimization is currently maybe realised in 4.7 kernel but this version have broken intel_pstate(check [this](http://www.phoronix.com/scan.php?page=article&item=linux-47-schedutil&num=1)) you can stay at old-stable and wait when reiser4 maintainer make 4.8 kernel patch then update to stable branch with reiser4(i'm also waiting reiser4 on 4.8)

**Comment by petter3k** [comment]
Stock arch linux kernel config with dell modules has them :-)

Få Outlook for Android<https://aka.ms/ghei36>



On Fri, Nov 4, 2016 at 12:12 AM +0100, "Sudokamikaze" <notifications@github.com<mailto:notifications@github.com>> wrote:


@petter3k<https://github.com/petter3k>
You want MUQSS_or_BLD+reiser4+optimization is currently maybe realised in 4.7 kernel but this version have broken intel_pstate(check this<http://www.phoronix.com/scan.php?page=article&item=linux-47-schedutil&num=1>) you can stay at old-stable and wait when reiser4 maintainer make 4.8 kernel patch then update to stable branch with reiser4(i'm also waiting reiser4 on 4.8)

-

**Comment by petter3k** [comment]
I will try anyway. IF you choose 4.7.10 then it should work on xps 9550 regarding pstates

Få Outlook for Android<https://aka.ms/ghei36>



On Fri, Nov 4, 2016 at 12:12 AM +0100, "Sudokamikaze" <notifications@github.com<mailto:notifications@github.com>> wrote:


@petter3k<https://github.com/petter3k>
You want MUQSS_or_BLD+reiser4+optimization is currently maybe realised in 4.7 kernel but this version have broken intel_pstate(check this<http://www.phoronix.com/scan.php?page=article&item=linux-47-schedutil&num=1>) you can stay at old-stable and wait when reiser4 maintainer make 4.8 kernel patch then update to stable branch with reiser4(i'm also waiting reiser4 on 4.8)

-

**Comment by petter3k** [comment]
I really just want the latest 4.7.x kernel with latest reiser4 and the best stuff for battery/performance. You can use the config template from a package like linux-ck or linux-pf for that, or stock arch linux kernel. Since this is a skylake platform would be great to have more support than I have atm...

**Comment by petter3k** [comment]
I really just want the latest 4.7.x kernel with latest reiser4 and the best stuff for battery/performance. You can use the config template from a package like linux-ck or linux-pf for that, or stock arch linux kernel. Since this is a skylake platform would be great to have more support than I have atm...

**Comment by petter3k** [comment]
I really just want the latest 4.7.x kernel with latest reiser4 and the best stuff for battery/performance. You can use the config template from a package like linux-ck or linux-pf for that, or stock arch linux kernel. Since this is a skylake platform would be great to have more support than I have atm...

**Comment by petter3k** [comment]
Linux-ck I think uses 4.7.8 and muqs with native packages. Maybe use as template? I dont want to mess too much around since this is a workstation.

**Comment by Sudokamikaze** [comment]
@petter3k 
I will create 4.7 branch and push sources to it(with reiser4/muqss/optimizations/etc) today

**Comment by petter3k** [comment]
Thats awesome, and thank you for that! Appreciated! 

I think 4.7.10 + muqss + skylake-optimizatons and latest reiser4 is best way to go with maybe template .config from Linux-ck or Linux-pf. But you probably know better :)

**Comment by Sudokamikaze** [comment]
@petter3k 
I use .config template from linux-zen because zen and lqx is compatible kernels
By the way, job is done, check [this](https://github.com/Sudokamikaze/XKernel-arch/tree/4.7-stable)
And before you start compiling open pkgbuild and define to `_use_optimization="IVYBRIDGE"` this `_use_optimization="SKYLAKE"`

MUQSS enabled in `_use_BFS="no"` 
Reiser4 enabled by default

**Comment by Sudokamikaze** [comment]
@petter3k 
And about modules, I will import DELL-related features from stock arch kernel just now

**Comment by petter3k** [comment]
Wow, thanks!!! :D trying it out in a minute.

**Comment by Sudokamikaze** [comment]
@petter3k 
If you don't have any problems with kernel i'll close issue, if you are still have issues reopen issue
