### ISSUE TITLE
NOT an issue: Very glad to see you updated this! Like the name Zenreiser too!

### ISSUE THREAD

**Issue by petter3k** [Sudokamikaze/XKernel-arch#2]
Thanks alot man!

**Comment by Sudokamikaze** [comment]
@petter3k 
I'm glad you enjoy my project!
I will support all branches with updates too!

**Comment by petter3k** [comment]
Perfect! There was an error with sha512 sums on config-i386 and config-386-pae but I just modified the PKGBUILD with the correct ones. I also modified the config to match my Dell XPS 15 laptop only, and compressing with lz4 instead of gzip etc. Nothing major, but very good project indeed! KUDOS!

**Comment by Sudokamikaze** [comment]
@petter3k 
The error seen yesterday but decided to fix in the next day
BTW sums updated and pushed to github!

**Comment by Sudokamikaze** [comment]
@petter3k 
Hi, i decided to ask. It worth to switch kernel compression to lz4?
And this done by simply switching in menuconfig?

**Comment by petter3k** [comment]
@Sudokamikaze Sorry for my late reply - Its absolutely better with LZ4. I modified the config to suit my laptop (max performance vs battery) and LZ4 is one of those newer compression-methods compared to atleast gzip even though gzip is fast too. LZO is also a great and IMO a better compression vs speed ratio, but at bootup I see no reason for the kernel to be ~5mb smaller in size (LZO) vs the great speed advantage of LZ4.

Just my 2 cents!

**Comment by Sudokamikaze** [comment]
@petter3k 
Thank you for reply!
I have already decided to change to LZ4

**Comment by Sudokamikaze** [comment]
@petter3k Hi mate! Do you still using my kernel?

If you do, [check](https://github.com/Sudokamikaze/linux-sk) my new fork of zen

Also i mentioned you in readme, check it! 

And many thanks for LZ4 inspiration in the past 👍
